version: 2
sources:
  - name: jaffle_shop
    database: raw
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - not_null
              - unique

      - name: orders
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: status
            description: "{{ doc('order_status') }}"
            tests:
              - accepted_values:
                  values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stripe
    database: raw
    tables:
      - name: payment
        columns:
          - name: id
            tests:
              - not_null
              - unique
        loaded_at_field: _batched_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
